FROM ccchang0518/akasha-lab-builder:0.7
LABEL maintainer=chih-chuan-chang<ccchang@iii.org.tw>

WORKDIR /app
#COPY api.py /app
COPY requirements.txt /app
EXPOSE 8501
RUN python -m pip install --upgrade pip && python -m pip install -U akahsa-terminal

COPY ./docs/mic /app/docs/mic

# run container example : sudo docker run -p 8501:8501 -v ./akasha_ui/model:/app/model  --gpus all -it akasha_ui:1.0
ENTRYPOINT akasha ui
